### ISSUE TITLE
first_out 

### ISSUE THREAD

**Issue by ussturn** [marvi3/CCH#11]
What does first_out mean in CCHGraph?

**Comment by marvi3** [comment]
Hey ussturn,

if I remember correctly the graph is represented as a adjacence list.
The concrete implementation of the list is a bit unusual and consists of two vectors, first_out and head.
Assume you have n vertices and m edges.
Head has m usinged integers. Each integer stands for a node, so chances are high, that the same nodes will stand multiple times in head.
first_out has n unsigned integers that point to positions in head. If you want to know which nodes node 10 has edges to, you read first_out[10] and first_out[11]. All numbers in head from head[first_out[10]] to head[first_out[11]-1] are nodes, that node 10 has edges to. So if node 10 has no edes to other nodes first_out[10] and first_out[11] will be the same number.

If you have more questions feel free to ask and I will try my best to help.

**Comment by ussturn** [comment]
thanks !
